import type { ClassValue } from 'clsx';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * A utility function to merge class names using clsx and tailwind-merge.
 * This function is similar to clsx, but it also supports merging of utility-first class names
 * (e.g. those generated by tailwindcss).
 *
 * @param inputs - A variable number of class names to merge.
 * @returns The merged class name.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
