import type { Metadata } from 'next';

import { GeistMono, GeistSans } from '@/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Next Enterprise Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
