import type { Metadata } from 'next';

import { GeistMono, GeistSans } from '@/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * A root layout body component that wraps the children in a div with Geist fonts.
 * It applies the GeistSans and GeistMono font variables to the div.
 * It also applies the antialiased class to the div.
 * @param {object} props - The props object.
 * @param {React.ReactNode} props.children - The children to render.
 * @returns {React.ReactElement} - The root layout body component.
 *
 * @note This only exist to satisfy the layout testing.
 */
export function RootLayoutBody({ children }: Readonly<{ children: React.ReactNode }>): React.ReactElement {
  return <div className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>{children}</div>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
