import type { Metadata } from 'next';

import '@fontsource-variable/geist';
import '@fontsource-variable/geist-mono';

import './globals.css';

export const metadata: Metadata = {
  title: 'Next Enterprise Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
